import type { OpenFilamentProfileV1 } from "@open-filament/canonical-profile";

export type PrusaConvertOpts = {
  inherits?: string;
};

function normalizeMaterial(code: string | null | undefined): string {
  return (code ?? "PLA").trim().toUpperCase().replace(/\s+/g, "-");
}

/**
 * Map material → PrusaSlicer system template (*PLA*, *PET*, *ABS*, *FLEX*).
 * ASA shares the ABS thermal family in stock PrusaResearch profiles.
 */
export function pickPrusaInherits(material: string): string {
  const m = material.toUpperCase();
  if (m === "PLA" || m === "PLA-SILK" || m.startsWith("PLA-")) return "*PLA*";
  if (m === "PETG" || m.startsWith("PETG") || m === "PET") return "*PET*";
  if (m === "ABS" || m === "ASA" || m.startsWith("ASA-") || m.startsWith("ABS-"))
    return "*ABS*";
  if (m === "TPU" || m === "FLEX" || m.startsWith("TPU")) return "*FLEX*";
  if (m === "PA" || m.startsWith("PA-") || m === "NYLON") return "*PLA*"; // safe fallback
  return "*PLA*";
}

function buildName(canonical: OpenFilamentProfileV1): string {
  const parts = [
    canonical.filament.manufacturerName,
    canonical.filament.productName,
    canonical.filament.variantName,
  ].filter(Boolean);
  if (parts.length > 0) return parts.join(" ");
  return canonical.title.replace(/^OF\s+/i, "");
}

function escIni(value: string): string {
  // Quote when spaces/specials present
  if (/[\s;#=]/.test(value)) {
    return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  return value;
}

/**
 * Convert canonical → PrusaSlicer filament user preset as INI text.
 * Import via File → Import → Import Config Bundle, or drop into
 * ~/Library/Application Support/PrusaSlicer/filament/
 */
export function convertCanonicalToPrusaFilamentIni(
  canonical: OpenFilamentProfileV1,
  opts: PrusaConvertOpts = {},
): string {
  const material = normalizeMaterial(canonical.filament.materialCode);
  const name = buildName(canonical);
  const inherits = opts.inherits ?? pickPrusaInherits(material);

  const nozzleTemp =
    canonical.thermal.nozzleTempOtherLayersC ??
    canonical.thermal.nozzleTempFirstLayerC;
  const bedTemp =
    canonical.thermal.bedTempOtherLayersC ??
    canonical.thermal.bedTempFirstLayerC;

  const lines: string[] = [
    `# Generated by Open Filament — vendor-independent calibration export`,
    `[filament:${name}]`,
    `inherits = ${inherits}`,
  ];

  if (canonical.filament.manufacturerName) {
    lines.push(`filament_vendor = ${escIni(canonical.filament.manufacturerName)}`);
  }
  lines.push(`filament_type = ${escIni(material.split("-")[0] ?? material)}`);
  if (canonical.filament.primaryColorHex) {
    lines.push(`filament_colour = ${canonical.filament.primaryColorHex}`);
  }
  if (canonical.filament.densityGCm3 != null) {
    lines.push(`filament_density = ${canonical.filament.densityGCm3}`);
  }
  lines.push(`filament_diameter = ${canonical.filament.diameterMm ?? 1.75}`);

  if (canonical.extrusion.flowRatio != null) {
    lines.push(`extrusion_multiplier = ${canonical.extrusion.flowRatio}`);
  }
  if (canonical.extrusion.maxVolumetricFlowMm3s != null) {
    lines.push(
      `filament_max_volumetric_speed = ${canonical.extrusion.maxVolumetricFlowMm3s}`,
    );
  }

  if (nozzleTemp != null) lines.push(`temperature = ${nozzleTemp}`);
  if (canonical.thermal.nozzleTempFirstLayerC != null) {
    lines.push(
      `first_layer_temperature = ${canonical.thermal.nozzleTempFirstLayerC}`,
    );
  } else if (nozzleTemp != null) {
    lines.push(`first_layer_temperature = ${nozzleTemp}`);
  }

  if (bedTemp != null) lines.push(`bed_temperature = ${bedTemp}`);
  if (canonical.thermal.bedTempFirstLayerC != null) {
    lines.push(
      `first_layer_bed_temperature = ${canonical.thermal.bedTempFirstLayerC}`,
    );
  } else if (bedTemp != null) {
    lines.push(`first_layer_bed_temperature = ${bedTemp}`);
  }

  if (canonical.cooling.fanMinPercent != null) {
    lines.push(`min_fan_speed = ${canonical.cooling.fanMinPercent}`);
  }
  if (canonical.cooling.fanMaxPercent != null) {
    lines.push(`max_fan_speed = ${canonical.cooling.fanMaxPercent}`);
  }
  if (canonical.cooling.fanDisableFirstLayers != null) {
    lines.push(
      `disable_fan_first_layers = ${canonical.cooling.fanDisableFirstLayers}`,
    );
  }

  if (canonical.retraction.retractionDistanceMm != null) {
    // Printer-level in many setups; still useful as filament override when supported
    lines.push(
      `; retraction_length override hint: ${canonical.retraction.retractionDistanceMm}`,
    );
  }

  if (canonical.dimensional?.shrinkagePercentXy != null) {
    lines.push(
      `; filament_shrinkage_xy hint: ${canonical.dimensional.shrinkagePercentXy}`,
    );
  }
  if (canonical.dimensional?.shrinkagePercentZ != null) {
    lines.push(
      `; filament_shrinkage_z hint: ${canonical.dimensional.shrinkagePercentZ}`,
    );
  }
  if (canonical.thermal.chamberTempC != null) {
    lines.push(`; chamber_temperature hint: ${canonical.thermal.chamberTempC}`);
  }

  if (canonical.extrusion.pressureAdvance != null) {
    // Stock Prusa uses firmware PA via start gcode on many printers; keep value visible.
    lines.push(
      `start_filament_gcode = "; Open Filament PA hint ${canonical.extrusion.pressureAdvance}\\n"`,
    );
  }

  const notes: string[] = ["Open Filament user preset"];
  if (canonical.provenance.isSyntheticFixture) {
    notes.push("Source: seed catalog data");
  }
  if (canonical.provenance.sourceNotes) {
    notes.push(canonical.provenance.sourceNotes);
  }
  lines.push(`filament_notes = ${escIni(notes.join(" — "))}`);
  lines.push("");

  return lines.join("\n");
}

/** Single-filament config bundle (importable as Config Bundle). */
export function convertCanonicalToPrusaConfigBundle(
  canonical: OpenFilamentProfileV1,
  opts?: PrusaConvertOpts,
): string {
  return (
    `# PrusaSlicer config bundle generated by Open Filament\n` +
    `# Import: File → Import → Import Config Bundle…\n\n` +
    convertCanonicalToPrusaFilamentIni(canonical, opts)
  );
}

export function suggestedPrusaFileName(canonical: OpenFilamentProfileV1): string {
  const name = buildName(canonical).replace(/[\/\\?%*:|"<>]/g, "-");
  return `${name}.ini`;
}
